-- MySQL Script generated by MySQL Workbench
-- Пн 04 мар 2019 17:18:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mycms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mycms` ;

-- -----------------------------------------------------
-- Schema mycms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycms` DEFAULT CHARACTER SET utf8 ;
USE `mycms` ;

-- -----------------------------------------------------
-- Table `mycms`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mycms`.`users` ;

CREATE TABLE IF NOT EXISTS `mycms`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `recovery` VARCHAR(255) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycms`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mycms`.`files` ;

CREATE TABLE IF NOT EXISTS `mycms`.`files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `files_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_timestamps_files`
    FOREIGN KEY (`files_id`)
    REFERENCES `mycms`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
